### ISSUE TITLE
Incorrect DICOM "View In Standard" Link

### ISSUE THREAD

**Issue by johndgiese** [innolitics/dicom-standard#10]
As reported in this thread:

https://groups.google.com/forum/#!topic/comp.protocols.dicom/YrMeGX-_9H8

> Go to: 
> 
> https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image/00189073 
> 
> Select "View in standard" (right side), incorrect link is: 
> 
> http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.2.2.html#sect_C.7.6.16.2.2.1 
> 
> should be instead: 
> 
> http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.2.html#sect_C.7.6.16.2.2.1

**Comment by johndgiese** [comment]
It seems possible that the first link is stale, because the standard has been updated.  If that is the case, it just means we need to finish hooking up the auto-sync functionality that we discussed with David Clunie.

**Comment by russellkan** [comment]
So it seems this is because the "wrong" table it links to actually includes the correct table: 
![image](https://user-images.githubusercontent.com/9055029/75002367-cbee3600-5429-11ea-8cfb-69dad162fb0d.png)

Clicking that leads to the table containing the attribute:
![image](https://user-images.githubusercontent.com/9055029/75002383-ddcfd900-5429-11ea-8ea1-e841e014a1d6.png)

This holds true for other items as well (where the items go multiple tables deep but all link only to the first table).
ex: https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image/00089121/0020000d
![image](https://user-images.githubusercontent.com/9055029/75002431-0d7ee100-542a-11ea-9a58-52d06879825f.png)
Should link to here but doesn't:
![image](https://user-images.githubusercontent.com/9055029/75002501-3dc67f80-542a-11ea-9578-860af480f2d6.png)
