### ISSUE TITLE
Missing Tag from module_to_attributes.json in attributes.json

### ISSUE THREAD

**Issue by SevKohler** [innolitics/dicom-standard#15]
Found an Error while checking the attributes.json against the module_to_attributes.json.
 "tag":"(0006,0001)" (dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.27.html#table_C.7.6.27-1) from module_to_attributes is missing in the attributes.json.

**Comment by johndgiese** [comment]
Thank you for reporting this @SevKohler

**Comment by fedorov** [comment]
I was using the extracted tables, and identified another issues that I don't quite understand at this point.

I came up with the list below by parsing the attributes from a dataset, and organizing attributes into modules. In the process of doing this, the following attributes were not found in the `module_to_attributes` table searching by `tag`. Most of them are not retired, so I am struggling a bit to understand why this would be happening.

![image](https://user-images.githubusercontent.com/313942/72559448-cd4ca180-3872-11ea-9def-ba8ec58b061e.png)

I did not check all of them against 2019e Part 3 PDF, but at least for some of them, it seems like there are some parsing issues in the code. `StackID` is in the "Multi-frame functional groups module" here: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.2.html#sect_C.7.6.16.2.2.

If this deserves a separate issue, please let me know and I will create it.

**Comment by johndgiese** [comment]
@fedorov thank you for reporting this list of attributes. I navigated to the [big HTML page](http://dicom.nema.org/medical/dicom/current/output/html/part03.html) for section 3 and started searching for the tag numbers in your list. As best I can tell, only the StackID (0020,9056) and InStackPositionNumber (0020,9057) appear in section 3.

My CTRL-F searches may be missing something, but it seems that these two attributes appear to be in a Macro which is not used in any CIODs in part 3.

Thus, as best I can tell, I would not expected any of these attributes to be present in `module_to_attributes`. (Of course, we are interested in extending our DICOM parser to include information about section 4 and other parts of the standard---but currently it does not)

**Comment by fedorov** [comment]
@johndgiese thank you for investigating!

I specifically called out StackID and that functional group, since I expected it would be used in enhanced multiframe CIODs. I searched now (I am searching in the PDF version of Part 3), and I could confirm that. As an example, ["Frame Content" macro](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.2.html#sect_C.7.6.16.2.2), which uses StackID, is used in ["Enhanced MR Image Functional Group Macros"](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.36.2.4.html).

However, I think I understand why the parser had a problem connecting those. [Enhanced MR module table](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.36.2.3.html) includes ["Multi-frame Functional Groups"](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.html), but (if I understand correctly), the IOD-specific content of this module is alluded to in the row 3 of that definition, which in turn is defined in ["Enhanced MR Image Functional Group Macros"](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.36.2.4.html), which includes "Frame Content", which includes StackID and InStackPositionNumber. So I don't think there is a way to parse this out automatically. 

I will discuss with @dclunie if multi-frame IOD definitions could list IOD-specific functional group macros included in the "Multi-frame Functional Groups" directly in the IOD table definition. I will also ask about those attributes from the list above that don't appear to be included in any modules.

**Comment by fedorov** [comment]
As a consequence of the above, Innolitics DICOM browser "analyzer" does not populate any of the Per-frame or Shared FGs for the multiframe input files:

![image](https://user-images.githubusercontent.com/313942/72621816-fbcc8a00-390f-11ea-93d7-cb90b5823dbd.png)

**Comment by fedorov** [comment]
@johndgiese I split off the conversation above into #16, since it is unrelated to the original issue.
