### ISSUE TITLE
Duplicate Entries in modules_to_attributes.json

### ISSUE THREAD

**Issue by johndgiese** [innolitics/dicom-standard#9]
There are two entries in `modules_to_attributes.json` which have the same value for the path key.  The duplicated value is: `"sr-document-content:0040a730:00700022"`.

We should investigate this, as it appears to be an error.

We should also check for other duplicates.

**Comment by Ouwen** [comment]
Thanks @johndgiese 

I was doing some preliminary checking and here are additional ones I have found.

```
2018/07/26 18:39:54 WARN: Duplicate Attribute Path: sr-document-content:0040a730:00081199
2018/07/26 18:39:54 WARN: Duplicate Attribute Path: sr-document-content:0040a730:00081199:00081150
2018/07/26 18:39:54 WARN: Duplicate Attribute Path: sr-document-content:0040a730:00081199:00081155
2018/07/26 18:39:54 WARN: Duplicate Attribute Path: sr-document-content:0040a730:00081199
2018/07/26 18:39:54 WARN: Duplicate Attribute Path: sr-document-content:0040a730:00081199:00081150
2018/07/26 18:39:54 WARN: Duplicate Attribute Path: sr-document-content:0040a730:00081199:00081155
2018/07/26 18:39:54 WARN: Duplicate Attribute Path: sr-document-content:0040a730:00700022
2018/07/26 18:39:54 WARN: Duplicate Attribute Path: sr-document-content:0040a730:00700023
2018/07/26 18:39:54 WARN: Duplicate Attribute Path: sr-document-content:0040a730:0070031a
``` 

Also thanks for making this repo open, it has really helped navigate the sprawling DICOM standard.

**Comment by russellkan** [comment]
Most of these duplicates are caused by the conditionally included attributes in [Table C.17-5](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.3.html#table_C.17-5).
![image](https://user-images.githubusercontent.com/9055029/80350544-80477680-8836-11ea-85e5-b9507a7b9536.png)

This can be handled by checking for these conditional statements and appending them to the attribute description, then combining all instances of the attribute with identical path into a single attribute object in the JSON.

The only other duplicate entry I could find in the current version is the path `rt-segment-annotation:00700084`, which appears to be an inconsistency with the standard: it shows up in [Table C.36.8-1](http://dicom.nema.org/medical/dicom/2019c/output/chtml/part03/sect_C.36.8.html) but reappears in [Table 10.9.2](http://dicom.nema.org/medical/dicom/2019c/output/chtml/part03/sect_10.9.2.html#table_10.9.2-1) with the same hierarchy level. I'm not sure if this is intended (since they have different descriptions), or if there is an issue with the hierarchy.

![image](https://user-images.githubusercontent.com/9055029/80350453-5beb9a00-8836-11ea-9386-454a9131523f.png)
---
![image](https://user-images.githubusercontent.com/9055029/80350497-6c9c1000-8836-11ea-8328-3b81d7a65f63.png)

**Comment by russellkan** [comment]
Proposed revision (for the browser):
![image](https://user-images.githubusercontent.com/9055029/80428015-8842fd00-88ae-11ea-8ebb-1976ecc22a33.png)

**Comment by johndgiese** [comment]
@russellkan this looks great!
