### ISSUE TITLE
Incorrect formula for relative time displayed for Frame Time Vector attribute (browser)

### ISSUE THREAD

**Issue by petermtate** [innolitics/dicom-standard#97]
**Bug description**
Incorrect formula displayed for relative time for a frame for `Frame Time Vector`

(note: I don't seen to have permissions to edit the labels)

**Steps for reproduction**
1. Navigate to `Frame Time Vector`. For example: https://dicom.innolitics.com/ciods/us-multi-frame-image/cine/00181065
2. In the `Details` view, examine the formula image for calculating the relative time for a frame
3. Formula is different from the standard (see: https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.5.html#sect_C.7.6.5.1.2)

**Expected behavior**

**Additional context (e.g. screenshots)**

expected: 
![image](https://github.com/innolitics/dicom-standard/assets/1037346/b739e10e-81d2-4f3e-8134-9c1a0554b832)

Actual:
 
![image](https://github.com/innolitics/dicom-standard/assets/1037346/867a85a0-4eae-4426-b7c6-67d0a50d945a)

**Comment by russellkan** [comment]
This appears to be a wrong image URL ([...image_2](https://dicom.nema.org/medical/dicom/current/output/html/figures/part03_withmml_image_2.svg) instead of [...image_3](https://dicom.nema.org/medical/dicom/current/output/html/figures/part03_withmml_image_3.svg)) but seems to be fixed in the current version. I believe this should be resolved upon the next update.

**Comment by russellkan** [comment]
Closing; resolved as of 3efa1627117bdfef24460da61b2389d3c2dbd375: 
<img width="665" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/c5e55ad6-6340-4b81-a218-1489292523fc">
